parameter_store:
  plain:
    - name: /example/aws/parameter1
      value: value1
    - name: /example/aws/parameter2
      value: value2
  secure:
    - name: /example/aws/parameter3
      private_key_path: private.pem
      value: orwRg85g5qKkpzX02TNoCq4/22Y08sGy2hpcRfiOThIc16dOQCZem4O+IfyzqBiMfh3UpDSRnY+5uli3y+YrM9PjIokVMNnSOstVlWJjAWrqWYWmaiAbcztarbcD98js7WJCUb6itQmJ9BfhAVC3WjlJvVJ7RJSx1jMZbvnIVt3Q3BKrCBrrKfTsZgp745fxho8FgYigccnyKoXG4NxF+YiQ4I9zqLUwfD5+LCcf49dvBe4H1YHOFk+qiQdaJ9J7oshexET+meNw7pn5KoGplsBOOW7fGTXabyNGmzNxr9QO3TNwh5tDgXC4iGYbDVM6i2I52SphVZ9gQx1WsI1Zmg==

oidc:
  - name: github
    issuer_url: "https://token.actions.githubusercontent.com"

ecr:
  - name: demo
  - name: demo2
    scan_on_push: true
  - name: demo3
    scan_on_push: false
    encryption_configuration:
      encryption_type: KMS
      kms_arn: arn:aws:kms:us-west-2:123456789012:key/12345678-1234-1234-1234-123456789012
    tags:
      Name: demo3
      Environment: dev
  - name: demo4
    scan_on_push: false
    encryption_configuration:
      encryption_type: AES256

eks:
  - name: demo
    version: "1.21"
    irsa:
      - name: demo
        service_account_name: aws-sa
        namespace: default
        role_arn: arn:aws:iam::123456789012:role/demo-role
        eks_issuer_url: https://oidc.eks.us-west-2.amazonaws.com/id/12345678901234567890
        service_account:
          name: aws-sa
          namespace: default
        tags:
          Name: demo
          Environment: dev
    tags:
      Name: demo
      Environment: dev

vpc:
  - name: demo
    cidr_block: 10.0.0.0/16
    region: ap-northeast-2
    nat_gateway_info:
      access: public
      az: ["a"]
    subnets:
      - az: a
        access: public
        cidr_block: 10.0.100.0/24
      - az: b
        access: public
        cidr_block: 10.0.101.0/24
      - az: c
        access: public
        cidr_block: 10.0.102.0/24
      - az: a
        access: private
        cidr_block: 10.0.0.0/24
      - az: b
        access: private
        cidr_block: 10.0.1.0/24
      - az: c
        access: private
        cidr_block: 10.0.2.0/24
      - az: a
        access: data
        cidr_block: 10.0.10.0/24
      - az: b
        access: data
        cidr_block: 10.0.11.0/24
      - az: c
        access: data
        cidr_block: 10.0.12.0/24
      - az: a
        access: protected
        cidr_block: 10.0.110.0/24
      - az: b
        access: protected
        cidr_block: 10.0.111.0/24
      - az: c
        access: protected
        cidr_block: 10.0.112.0/24
    route_tables:
      - access: public
        route_table_assocations:
          - subnet_az: a
          - subnet_az: b
          - subnet_az: c
        route_table_routes:
          - destination: 0.0.0.0/0
            target_resource: internet_gateway
      - access: private
        route_table_assocations:
          - subnet_az: a
          - subnet_az: b
          - subnet_az: c
        route_table_routes:
          - destination: 0.0.0.0/0
            target_resource: nat_gateway
            az: a
    security_groups:
      - name: demo
        ingress_rules:
          http:
            ingress_from_port: 80
            ingress_to_port: 80
            ingress_protocol: tcp
            cidr_blocks: ["0.0.0.0/0"]
          https:
            ingress_from_port: 443
            ingress_to_port: 443
            ingress_protocol: tcp
            cidr_blocks: ["0.0.0.0/0"]
          self_custom:
            ingress_from_port: 0
            ingress_to_port: 0
            ingress_protocol: "-1"
            self: true
        egress_rules:
          all:
            egress_from_port: 0
            egress_to_port: 0
            egress_protocol: "-1"
    tags:
      Name: demo
      Environment: dev
